services:
  db:
    image: postgres:16
    container_name: todo-app-db
    environment:
      POSTGRES_DB: todo_app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d todo_app_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: todo-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo_app_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  postgres-data:
